name: Deploy to Azure Functions

on:
  push:
    branches:
      - main  # Set your branch name here

env:
  AZURE_FUNCTIONAPP_NAME: testtest12344       # Set your Azure Function App name here
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'                 # Path to your function app code, usually the root folder
  AZURE_FUNCTIONAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}  # GitHub secret name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Node 14.x Environment
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'  # Set to your Node.js version

    - name: 'Resolve Project Dependencies Using Npm'
      shell: bash
      run: npm install

    - name: 'Run Build Task'
      shell: bash
      run: npm run build  # Build your code if applicable

    - name: 'Deploy to Azure Functions'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ env.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
