name: Build and deploy Node.js app to Azure Web App - ChuckBot

on:
  push:
    branches:
      - with-fixes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      timestamp: ${{ steps.get_timestamp.outputs.timestamp }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
          
          
      - name: Generate deployment package
        run: zip -r release.zip .
        
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release.zip

      - name: Get the current timestamp
        id: get_timestamp
        run: echo "::set-output name=timestamp::$(date +'%Y%m%d%H%M%S')"
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: release
      
      - name: Unzip artifact for deployment
        run: unzip release.zip -d ./deploy
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "ChuckBot"
          slot-name: "Production"
          package: ./deploy

 